#  Customer Segmentation - Data Cleaning

##  Objective
The goal of this notebook is to clean and prepare customer data for segmentation using clustering techniques.

## Business Context
Customer segmentation relies on identifying patterns in customer behaviour.

To ensure meaningful clusters:
- Data must be accurate
- Missing values must be handled
- Features must reflect real customer behaviour

Poor data quality would lead to unreliable customer segments.

In [2]:
import pandas as pd
import numpy as np

df = pd.read_excel('../Data/raw/Online_Retail.xlsx')

## Initial Data Inspection

We inspect:
- Data types
- Missing values
- Basic statistics

###  Purpose
This helps identify data quality issues that must be resolved before clustering.

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

## Data Cleaning

Data cleaning is performed to ensure the dataset is suitable for segmentation.

This includes:
- Handling missing values
- Correcting data types
- Removing invalid or inconsistent records

### Why This Matters for Clustering

Clustering algorithms rely on patterns in the data.

If the data contains:
- Missing values
- Incorrect formats
- Noise

Then the resulting customer segments will be unreliable.

Clean data ensures that clusters reflect real customer behaviour rather than data issues.

In [6]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.isnull().sum()

invoiceno           0
stockcode           0
description      1454
quantity            0
invoicedate         0
unitprice           0
customerid     135080
country             0
dtype: int64

In [7]:
df = df.dropna(subset =["customerid"])

In [8]:
df["description"]= df["description"].fillna('Unknown')

In [11]:
df['customerid'] =df['customerid'].astype(int)
df['invoicedate']= pd.to_datetime(df['invoicedate'])

In [12]:
df.duplicated().sum()

np.int64(5225)

In [13]:
df = df.drop_duplicates()

In [14]:
df =df[~df['invoiceno'].astype(str).str.startswith('C')]

In [15]:
df = df[df['quantity'] >0]
df = df[df['unitprice']>0]

In [17]:
df['total_price']=df['quantity'] * df['unitprice']

In [18]:
df.describe()

,quantity,invoicedate,unitprice,customerid,total_price
count,392692.000000,392692,392692.000000,392692.000000,392692.000000
mean,13.119702,2011-07-10 19:13:07.771892480,3.125914,15287.843865,22.631500
min,1.000000,2010-12-01 08:26:00,0.001000,12346.000000,0.001000
25%,2.000000,2011-04-07 11:12:00,1.250000,13955.000000,4.950000
50%,6.000000,2011-07-31 12:02:00,1.950000,15150.000000,12.450000
75%,12.000000,2011-10-20 12:53:00,3.750000,16791.000000,19.800000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,168469.600000
std,180.492832,NaN,22.241836,1713.539549,311.099224

In [20]:
df.to_csv("../Data/processed/online_retail_cleaned.csv", index = False)

##  Summary

- Data has been cleaned and validated
- Missing values have been handled
- Data types have been corrected
- The dataset is now consistent and reliable

##  Next Steps

- Create behavioural features (e.g. spending, frequency)
- Scale features for clustering
- Apply clustering algorithms (e.g. KMeans)

##  Conclusion

This notebook ensures that the dataset is ready for segmentation by removing inconsistencies and preparing the data for meaningful clustering.